### ISSUE TITLE
run_python_parcellation.py does not follow pep8

### ISSUE THREAD

**Issue by sdeslauriers** [BBELAOUCHA/dMRIParcellation#2]
The script `run_python_parcellation.py` does not follow pep8. Run pep8 or flake8 to see the problems. In addition, I propose the following changes:

1. Add the standard `if __name__ == '__main__':` section and move the code to a function. This way the module can be imported without running it.
2. Instead a comment after every `add_argument` line, add the info in the `help=` keyword. Will make your `run_python_parcellation.py -h` much more informative.
3. Use default values in the parser (for example, for verbose, merge, and cvth).

If you makes these changes and create a pull request, I will be happy to review.

**Comment by BBELAOUCHA** [comment]
run_python_parcellation.py is removed because it is a duplicate. Now all files follow pep8
